name: Build Android APK

on: [push]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.37

      - name: Setup buildozer.spec
        run: |
          buildozer init
          # VVV OSTATECZNA ZMIANA WYMAGAŃ VVV
          # Używamy najnowszej stabilnej wersji pyjnius i nowszej, ale sprawdzonej wersji cython
          sed -i 's|^#requirements = .*|requirements = python3,kivy,pyjnius==1.6.0|' buildozer.spec
          echo "android.build_tools_version = 34.0.0" >> buildozer.spec

      - name: Build with Buildozer
        run: |
          yes | buildozer -v android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: quiz-kpp-apk
          path: bin/*.apk